### ISSUE TITLE
open collapsed

### ISSUE THREAD

**Issue by danielemontesi** [StartBootstrap/startbootstrap-simple-sidebar#11]
how can i open my page with sidebar already collapsed?

**Comment by atomtigerzoo** [comment]
You can just add the class `toggled` to the `wrapper`-div. It will then be hidden on load:

```
<div id="wrapper" class="toggled">
```

**Comment by davidtmiller** [comment]
Thanks @atomtigerzoo for answering this one - closing this for now.

**Comment by surgiie** [comment]
adding the class toggled makes smaller screens show sidebar? How can i just collapse sidebar no matter what screen size? @davidtmiller @atomtigerzoo
