### ISSUE TITLE
Feature Request: Need to add support for Fixed navbar

### ISSUE THREAD

**Issue by ravimallya** [StartBootstrap/startbootstrap-simple-sidebar#15]
Hi. 

This is a good plugin. However, I have tried your solution with fixed navbar and found that fixed navbar is not sliding when click on toggle button. 

It would be better, if you give support for that, with an addition to fixed navbar and footer as well as swipe event in mobile browser.

**Comment by davidtmiller** [comment]
I'll look into it, possibly as a new template.

**Comment by woodwardmatt** [comment]
Same here :+1:

**Comment by davidtmiller** [comment]
This will be more of an enhancement. In the meantime you can check out the SB Admin and SB Admin 2 theme for a sidebar plus fixed navigation. I'm going to keep this in mind though for a future template. It would be like an admin theme with just the navigation component and just a blank area. Perhaps a SB Admin Lite or something like that. Keeping this open for now after revisiting this.
