### ISSUE TITLE
content doesnt go off screen on mobile in ios9 - shrinks instead

### ISSUE THREAD

**Issue by rvrtnce** [StartBootstrap/startbootstrap-simple-sidebar#19]
I upgraded to ios9 today and now when I toggle the menu on my iPhone instead of the page-content shifting off-screen to the right when the menu comes out everything shrinks and the menu and all my content shows on the page.

When I first load the page if I pinch and zoom slightly then release and allow it to go back to fullscreen then hit then menu icon - it works fine.

I have the same issue with the demo as well as my version.

Ideas?

**Comment by ghost** [comment]
This is the same issue as #16, I think. It's been brought up on the [Apple Developer Forums](https://forums.developer.apple.com/thread/13510). The solution is to add `shrink-to-fit=no` to the viewport meta tag. For example, this works for me: `<meta name="viewport" content="width=device-width shrink-to-fit=no">`. I've made a pull request, I hope @davidtmiller will accept it!

**Comment by rvrtnce** [comment]
That was it. Thank you so much.

**Comment by davidtmiller** [comment]
Hey @brortao thanks for the fix. I will get this added soon.

**Comment by davidtmiller** [comment]
Added this in!
