### ISSUE TITLE
Android Browser

### ISSUE THREAD

**Issue by nuncloid** [StartBootstrap/startbootstrap-simple-sidebar#2]
Works fine in most major browsers I tested but… did you try it on the Android native Browser? Does unfortunately not work at all here.

**Comment by davidtmiller** [comment]
I haven't tried it in Android lately. I think I've decided that I am going to revise this theme completely once I have a bit of time. Thanks for the comment though, it's just more justification to rebuilt this template a bit better.

**Comment by 20v100** [comment]
+1 for making this template Android compatible.

**Comment by npersson** [comment]
Tried and it does work on Android 4.4 native browser

**Comment by tindzk** [comment]
No, the sidebar does not take into account the screen size, making manual zooming necessary. It should behave in the same way as [Mopidy-MusicBox-Webclient](https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/tree/master/screenshots).

**Comment by davidtmiller** [comment]
I still don't have a fix for this. If anyone wants to take a stab at it feel free to submit a pull request!

**Comment by davidtmiller** [comment]
Going to close this for now since there is going to be some redesigning coming up with the BS4 shift.
