### ISSUE TITLE
Help with sidebar

### ISSUE THREAD

**Issue by lsvargasp** [StartBootstrap/startbootstrap-simple-sidebar#21]
Hello 
I don't know if this is the correct place to post, but it would be of great help if i could understand a pretty basic thing. I need to know how to connect properly the sidebar buttons, i need put the link in href but i need the content to be shown in the same page in the blank space.
Thanks

**Comment by davidtmiller** [comment]
Yes, so you would need to be using some sort of JS framework in order to achieve this effect.
