### ISSUE TITLE
Sidebar Reloading Issue

### ISSUE THREAD

**Issue by kswebteam** [StartBootstrap/startbootstrap-simple-sidebar#28]
Thank for for this! This works great for one of my projects. The one thing that I noticed is that when I have my website on Chrome, the sidebar will stay open page to page. But in Internet explorer, the sidebar will reanimate from closed to open. It's as if it's taking longer to load the javascript or something. 

Is there a way I can make the sidebar not reanimate (slide) to open when I go page to page in Internet Explorer?

**Comment by fabio7** [comment]
I had the same problem, if you still need I solved by removing the transition effects on desktop:

```
@media(min-width:768px) {
    #wrapper {
        padding-left: 250px;
        -webkit-transition: none;
        transition: none;
    }
[...]
    #sidebar-wrapper {
        width: 250px;
        -webkit-transition: none;
        transition: none;
    }
[...]
}
```

**Comment by davidtmiller** [comment]
Keep in mind that removing the transition on desktops will remove the transition when the toggle button is pressed as well on desktops. I will have to explore some more permanent solutions to this when I have some time, but if anyone has any ideas feel free to share them!

**Comment by fabio7** [comment]
It's true. I forgot to mention that I had disabled the toggle button on desktop, because it didn't serve for my purposes
