### ISSUE TITLE
Position won't stay fixed on Android Chrome 49.0

### ISSUE THREAD

**Issue by Wardevour** [StartBootstrap/startbootstrap-simple-sidebar#34]
It works flawlessly on the latest version of Chrome and Firefox on a desktop but when I try on my phone the sidebar wont stay fixed. It scrolls with the main-page-content. I'm hoping its just an error on my end.

Otherwise it's beautiful and I love you ;)

**Comment by jonasbleyl** [comment]
See #35

**Comment by davidtmiller** [comment]
I am not sure on this one! I will have to get my hands on an Android device and see this behavior in action.

**Comment by Wardevour** [comment]
It turned out that it was any WebKit browser and it didn't work on Desktop
either. I was able to fix it by giving the entire body position: fixed;
when the side panel opened, but it doesn't feel quite right. I haven't
tried the fix above though.
