### ISSUE TITLE
inside modal?

### ISSUE THREAD

**Issue by betoxx** [StartBootstrap/startbootstrap-simple-sidebar#36]
When I place it inside a bootstrap modal all goes outside the modal.

**Comment by TammyD79** [comment]
Have you found a way to get this to work? I have the same problem.

**Comment by TammyD79** [comment]
If you make the modal full screen it works..

.modal-dialog {
  width: 100%;
  height: 100%;
  margin: 0;
  padding: 0;
}

.modal-content {
  height: auto;
  min-height: 100%;
  border-radius: 0;
}

**Comment by davidtmiller** [comment]
Not sure on this one, if anyone wants to take a stab at it let me know!
