### ISSUE TITLE
Bower?

### ISSUE THREAD

**Issue by soichih** [StartBootstrap/startbootstrap-simple-sidebar#4]
Is there anyway you could publish individual css / js on bower?

**Comment by sunshineo** [comment]
+1

**Comment by tylerbrazier** [comment]
+1

**Comment by dandv** [comment]
https://www.quora.com/Why-use-Bower-when-there-is-npm

**Comment by moravcik** [comment]
since the only extra code is the CSS you can add to your bower.json:

```
  "dependencies": {
    "simple-sidebar": "IronSummitMedia/startbootstrap-simple-sidebar"
  },
  "overrides": {
    "simple-sidebar": {
      "main": [
        "css/simple-sidebar.css"
      ]
    }
  }
```

and wiredep will catch this dependency normally
do not forget to depend on bootstrap itself which you probably already do

**Comment by soichih** [comment]
Thanks. That worked - although I am not familiar with the content of "wiredep".

**Comment by davidtmiller** [comment]
NPM is kind of the winner at the moment. Moving into BS4 I'll be making NPM modules for all of the templates on Start Bootstrap. There is going to be some considerable restructuring and design changes coming up soon, so I'll look into adding NPM modules for this template and others. Thanks for the suggestion / +1's.

**Comment by davidtmiller** [comment]
I'll definitely be looking into an npm package for this template in the near future. It's still on the to-do list, which is quite long :\

**Comment by ripper2hl** [comment]
bower package please ! :+1:

**Comment by sunshineo** [comment]
Guys, check out angular2 material. It has a side bar. However, it means your project need to use angular2

**Comment by davidtmiller** [comment]
An npm package has been created, and Bower is looking like it's on the downslide, but I will probably add a Bower package in the Bootstrap 4 build anyways.
