### ISSUE TITLE
Sidebar Scrolling Issue

### ISSUE THREAD

**Issue by surgiie** [StartBootstrap/startbootstrap-simple-sidebar#40]
I am using this for one of my projects but seem to have an issue with the scrolling for the side bar. I cannot for some reason see all of my links that i have on my side bar. There is a scroll bar for me to scroll through sidebar navigation but i can only scroll down so far and i cant see all of my links. I know they are there because if i zoom out browser i can see it. Is there a css property i have to adjust to be able to scroll all the way down or see all my list on the sidebar?

**Comment by tylerneu** [comment]
I see the same. I'm currently working around it by changing the position of `#wrapper.toggled #page-content-wrapper` to `fixed`.

**Comment by surgiie** [comment]
I did a temporary work around by changing the height of the sidebar. But now my page content wrapper becomes unscrollable. The scrolling for the content becomes disabled. So im having this problem in my content wrapper now. So if there is content/data there, and its long enough i cant scroll when i close toggle the sidebar but when the sidebar is there the content is scrollable? where can i make the content scrollable if the sidebar is not toggled? @tylerneu

**Comment by ayamamori** [comment]
I wander your problem is the same one as mine, but I also have a problem that I can't scroll the sidebar until the end and only could scroll about 50px higher position of the end.

The work around I figured out is:
```css
.sidebar {
  min-height: initial;
}
```
This is to clear `min-height: 100%;` defined in the plug in.
