### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by renanpro03** [StartBootstrap/startbootstrap-simple-sidebar#42]
Hi, are you thinking about update to bootstrap 4?

**Comment by wsloth** [comment]
Seconding this. It does not play well with the new flex grid, but I'd love to use this in a BS4 project.

**Comment by davidtmiller** [comment]
I am in the process of converting everything on Start Bootstrap to Bootstrap 4 alpha since the beta release is creeping closer.

This template isn't 'low hanging fruit' however, so I'll be working on it soon to figure out how to make a really nice BS4 version that functions similarly.

**Comment by 1nv1n** [comment]
Based on [1f6ac5d7ee594ada14a8dc9378ddeda3c85fdded](https://github.com/BlackrockDigital/startbootstrap-simple-sidebar/commit/1f6ac5d7ee594ada14a8dc9378ddeda3c85fdded), this issue can be closed, right?

**Comment by davidtmiller** [comment]
Done!
