### ISSUE TITLE
Bower repository looks odd

### ISSUE THREAD

**Issue by HarelM** [StartBootstrap/startbootstrap-simple-sidebar#44]
https://libraries.io/bower/startbootstrap-simple-sidebar
clone address is different than repository address, can you fix it?

**Comment by karolyi** [comment]
+1

**Comment by davidtmiller** [comment]
The organization name was changed to BlackrockDigital from IronSummitMedia. Someone came in and sniped the IronSummitMedia name shortly after it was deleted on GitHub and I've been unable to get GitHub to make any actions to close down that account.

I am trying to contact Bower to get the old packages deleted and freed up so I can create them under the new organization name.

**Comment by HarelM** [comment]
Sounds like the issue is not resolved though, right? If it's not resolved please keep this issue open...

**Comment by davidtmiller** [comment]
It's across all themes and I've added it to a master issues list, so it will be covered in a larger meta-update.
