### ISSUE TITLE
please, how to change black sidebar background color

### ISSUE THREAD

**Issue by dataSQL** [StartBootstrap/startbootstrap-simple-sidebar#45]
please, how to change black sidebar background color?

Any assistance or suggestions greatly appreciate.

**Comment by Roman45** [comment]
simple-sidebar.css
line 25 #sidebar-wrapper {
......
    background: #000;

**Comment by dataSQL** [comment]
Excellent!  Shall try.

Thank you!

**Comment by dataSQL** [comment]
That was right on!  Thank you, would you happen to also know the line number for the top header background color?

**Comment by Roman45** [comment]
"the top header background color" ?

**Comment by dataSQL** [comment]
Thank you Roman45, my mistake.
