### ISSUE TITLE
Horizontal nav on mobile rather than hiding

### ISSUE THREAD

**Issue by codewithtyler** [StartBootstrap/startbootstrap-simple-sidebar#48]
Currently, when on mobile this template will hide the navigation menu. I'd like to make it so that instead of hiding the navigation it will change and just show the brand and a hamburger menu (like normal horizontal menus do). How can I do this?

**Comment by themeaningofmeaning** [comment]
Yes, I'd also like to know how to do this

**Comment by HisServant77** [comment]
Could this be done by simply added the code that creates the top menu, into the toggle call of the side menu?
