### ISSUE TITLE
strange transition when add multiple select with a selected option in content!

### ISSUE THREAD

**Issue by pprolancer** [StartBootstrap/startbootstrap-simple-sidebar#49]
Hi @davidtmiller 
I have faced with an strange bug. I have a bad transition when I put an select element with a selected option in content.

to re-produce this bug, I have changed your sample from here:
https://blackrockdigital.github.io/startbootstrap-simple-sidebar/

I have added this line on page-content-wrapper under `<h1>Simple Sidebar</h1>:`

`<select multiple="multiple"><option selected>Test</option></select>`

so you will see we will have bad transition when we have a select tag like above line in content.

I have checked that on chrome version 55.0.2883.87 
I haven't this issue on firefox.

this is very bad bug.
I will be thank you if you could resolve this soon.
Thanks

**Comment by davidtmiller** [comment]
Transitions should look good now since the flexbox update.
