### ISSUE TITLE
Align to the right instead of left

### ISSUE THREAD

**Issue by boilemmashem** [StartBootstrap/startbootstrap-simple-sidebar#54]
I'm trying to get the sidebar to appear on the right instead of the left. I have essentially changed all the css properties from left -> right and right -> left.

It works for the most part, but while in mobile view the content is not animated, and 'pops' to the left when the menu is opened. How could this be fixed so the animation works correctly?

**Comment by davidtmiller** [comment]
Basically change the margin-left stuff to margin-right stuff and move the sidebar element below the the page content in the HTML.
