### ISSUE TITLE
npm i startbootstrap-simple-sidebar  Then?

### ISSUE THREAD

**Issue by otgerpeidro** [StartBootstrap/startbootstrap-simple-sidebar#64]
Hi,

I'm using expressjs with ejs and I would like to use this template. I have installed with npm i startbootstrap-simple-sidebar and I have the package on node_modules
How do I have to use it? What do I supose to put in my app.js file?

Thanks in advance.

Regards

**Comment by davidtmiller** [comment]
It is in your `node_modules` at that point, and how you want to import it into your project is up to you.
