### ISSUE TITLE
Firefox - Not open by default

### ISSUE THREAD

**Issue by aleisha** [StartBootstrap/startbootstrap-simple-sidebar#65]
In Firefox the side nav bar isn't open by default for a desktop.  It's open by default on Chrome.  Do I need to do an overwrite somewhere to make this behavior work on firefox?

**Comment by seanpaulkelley** [comment]
For me, using Chrome 61.0.3163.100 and Firefox 57.0.1 
The nav bar is collapsed by default on
https://blackrockdigital.github.io/startbootstrap-simple-sidebar/
and of course on my own local copy.

**Comment by seanpaulkelley** [comment]
To work around this issue I changed the css to display the sidebar on wider screen and hide toggle button on large  screen also.  I might be nice to allow toggle to hide on larger screen however.

```
@media (min-width: 768px) {
  #wrapper {
    padding-left: 250px;
  }

  #wrapper #sidebar-wrapper {
    width: 250px;
  }

  #wrapper #page-content-wrapper {
    position: relative;
    margin-right: 0;
  }
  #menu-toggle {
    display: none;
  }
}
```

**Comment by davidtmiller** [comment]
Should be fixed with the flexbox update.
