### ISSUE TITLE
How to use in yii2

### ISSUE THREAD

**Issue by umakantm** [StartBootstrap/startbootstrap-simple-sidebar#7]
please help ....how to use this plugin in yii2

**Comment by bigbrush** [comment]
You could create a layout in Yii 2. See http://www.yiiframework.com/doc-2.0/guide-structure-views.html#layouts

**Comment by davidtmiller** [comment]
Thanks @bigbrush

**Comment by CallumBrankin** [comment]
Has anyone managed to do it?
