### ISSUE TITLE
How to integrate Simple Sidebar

### ISSUE THREAD

**Issue by noloader** [StartBootstrap/startbootstrap-simple-sidebar#72]
I think this is Blackrock Digital's bug: [How to use side nav bar in angular 6?](https://stackoverflow.com/q/52360419/608639) It is a documentation bug.

The project's README says:

> After downloading, simply edit the HTML and CSS files included with the template in your favorite text editor to make changes.

The README never says what changes to make in a prescriptive manner. That is, the README should provide the exact steps a user needs to perform instead of saying *"[just] make changes"*.

For users unfamiliar with the library or project, they need exact steps to perform.

**Comment by milandimun** [comment]
Hi @noloader is it still open ? I could work on this.

**Comment by davidtmiller** [comment]
This is just a static HTML template, so how users decided to implement it into various frameworks is up to them.
