### ISSUE TITLE
How to use this code in Angular 6?

### ISSUE THREAD

**Issue by ruwanmadhusanka** [StartBootstrap/startbootstrap-simple-sidebar#73]
Can anyone explain how to use this in angular 6 project?

**Comment by webcourse-ng** [comment]
I'm taking a shot at implementing this layout with my Angular 7 project. Have you made any progress on this front?

**Comment by davidtmiller** [comment]
This is just a static HTML template, so how users decided to implement it into various frameworks is up to them.
