### ISSUE TITLE
Show sidebar by default and disappear on small device.

### ISSUE THREAD

**Issue by stockersky** [StartBootstrap/startbootstrap-simple-sidebar#74]
Hello,
First of all, thanks for the code :-) !
Actually, the behavior of the sidebar is a bit strange...
I think it should be displayed on wide screens (having the button to make it disappear), and when the screen shrinks (or smaller devices), the sidebar should disappear and the button should make it take the whole screen.
I could simple activate the sidebar by default with just adding the class "toggle" on the main wrapper.
`<div id="wrapper" class="toggled">`

But could you give guidance how to make the sidebar disappear on smaller devices (the @media part of the css), please?

**Comment by davidtmiller** [comment]
Basically just take what is in the @media and make those settings default. The end result should have no media queries in the CSS.
