### ISSUE TITLE
404 Error thrown on favicon

### ISSUE THREAD

**Issue by sudheesh001** [StartBootstrap/startbootstrap-simple-sidebar#8]
Error details: `Failed to load resource: the server responded with a status of 404 (Not Found)`
URL : `http://ironsummitmedia.github.io/startbootstrap-simple-sidebar/`

**Comment by dataforxyz** [comment]
is this solved? I cant seem to find it.

**Comment by sudheesh001** [comment]
Nope, it still throws up the same error on console.
http://ironsummitmedia.github.io/startbootstrap-simple-sidebar/

**Comment by davidtmiller** [comment]
There isn't a favicon on this template as far as I know...is that what you're referencing?

**Comment by davidtmiller** [comment]
The new URL is here: http://blackrockdigital.github.io/startbootstrap-simple-sidebar/
