### ISSUE TITLE
Can't change the sidebar color

### ISSUE THREAD

**Issue by zwoosks** [StartBootstrap/startbootstrap-simple-sidebar#81]
Hi. I tried to change the sidebar color in the bootstrap.css but I couldn't... what class should I modify to change the color?

**Comment by zwoosks** [comment]
I changed .bg-light background-color to #FF7F50 and anything happens.

**Comment by davidtmiller** [comment]
The sidebar uses the `bg-light` utility class which is set to `!important`. The easiest way to change the background color of the sidebar would be to change that `bg-light` class to something else.
