### ISSUE TITLE
Bug with bootstrap grid

### ISSUE THREAD

**Issue by storres93** [StartBootstrap/startbootstrap-simple-sidebar#9]
I have a bootstrap grid (col-xs- etc etc) on the page content, and with this side navbar the grid overflows, bootstrap takes full window width instead of just the page content container width.

How can I solve this?

Thank you

**Comment by ghost** [comment]
I also have the same problem. Is this a new issue or is this the way it was designed?

**Comment by mursalinalinnk** [comment]
so do i.how do we solve this issue ?

**Comment by ghost** [comment]
I made the following change to the .container Class in bootstrap, and it gets me pretty far...
@media (min-width: 768px) {
  .container {
    width: 480px;
  }
}
@media (min-width: 992px) {
  .container {
    width: 710px;
  }
}
@media (min-width: 1200px) {
  .container {
    width: 920px;
  }

**Comment by dataforxyz** [comment]
this is the easy fix. 

body {
    overflow-x: hidden;
}

**Comment by davidtmiller** [comment]
Thanks @bobsburgers for the change, I'll look into adding this into the template.

**Comment by davidtmiller** [comment]
Added this change in thanks!
