### ISSUE TITLE
Not working on Chrome

### ISSUE THREAD

**Issue by juanjzb** [StartBootstrap/startbootstrap-simple-sidebar#94]
Template is not working on Chrome

**Comment by Kelo** [comment]
I'm getting the same issue. Works fine in safari, but not in chrome.

**Comment by Hamfri** [comment]
Would you mind adding more information about what is not working? I tested it on **chrome Version 90.0.4430.93** and everything seems okay.

**Comment by Hamfri** [comment]
Would you mind adding more information about what is not working? I tested it on **chrome Version 90.0.4430.93** and everything seems okay.

**Comment by Kelo** [comment]
I was having an issue with the template on Chrome. Until I realised that the browser wasn't hard refreshing and using an old version from the cache... I'd suggest clearing the website cache or trying holding CTRL then hit F5
